barbara/urls.py
from django.urls import path, re_path
from . import views
from django.utils.translation import gettext_lazy as ugettext_lazy
app_name = "barbara"

urlpatterns = [
path('', views.index, name='index'),
path('about/', views.about, name='about'),
path('contact/', views.contact, name='contact'),
path('services/', views.services, name='services'),
]

salon/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from barbara import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.conf.urls import url

urlpatterns = [ 
    path('i18n/', include('django.conf.urls.i18n')), 
    path('admin/', admin.site.urls),
    url(r'set_language/(?P<user_language>\w+)/$', views.set_language_from_url, name="set_language_from_url"),
    path('', include('barbara.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barbara/models.py
from django.db import models

# Create your models here.

barbara/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from django.utils.translation import gettext as _
from django.utils.translation import ugettext_lazy

OPTIONS = (
    ('', ugettext_lazy('Izberi...')),
    ('Google', 'Google'),
    ('Facebook', 'Facebook'),
    ('MojaDejavnost.si', 'MojaDejavnost.si'),
    ('prijatelj/znanec', ugettext_lazy('prijatelj/znanec')),
    ('drugo', ugettext_lazy('drugo'))
)

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, label =  ugettext_lazy('Ime in priimek'))
    number = forms.CharField(max_length=15, required=True, label = ugettext_lazy('Telefonska številka'))
    email = forms.EmailField(max_length=100, required=True, label = ugettext_lazy("E-pošta"))
    reputation = forms.ChoiceField(choices=OPTIONS, required=False, label= ugettext_lazy("Kako si slišal zame"))
    message = forms.CharField(widget=forms.Textarea, max_length=2000, required=True, label= ugettext_lazy("Sporočilo"))
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.helper = FormHelper()
            self.helper.layout = Layout(
                Row(
                    Column('name', css_class='form-group col-md-6 mb-0'),
                    Column('number', css_class='form-group col-md-6 mb-0'),
                    css_class='form-row'
                ),
                 Row(
                    Column('email', css_class='form-group col-md-6 mb-0'),
                    Column('reputation', css_class='form-group col-md-6 mb-0'),
                    css_class='form-row'
                ),
                'message',
                Submit('submit', _('Pošlji'))
            )

barbara/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from .forms import ContactForm
from django.core.mail import send_mail
from django.contrib import messages
from django.utils.translation import gettext
from django.utils import translation
from django.http import HttpResponseRedirect

# Home page
def index(request):
    return render(request, 'barbara/index.html')

#About page
def about(request):
    return render(request, 'barbara/about.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            sender_name = form.cleaned_data['name']
            sender_email = form.cleaned_data['email']
            sender_number = form.cleaned_data['number']
            feedback = form.cleaned_data['reputation']
            message = "To sporočilo je bilo poslano preko spletne strani.\n\n" + "Ime in priimek: " + sender_name + "\nTelefon: " + sender_number + "\nE-pošta: " + sender_email + "\n\nSporočilo:\n" + form.cleaned_data['message'] + "\n\n\nSlišal/-a sem zate preko:" + str(feedback)

            sender = "Poizvedba " + sender_name + " " + "<" + sender_number + ">"
            
            #send_mail(sender, message, sender_email, ['barbara.bergant3@gmail.com'])
            from django.core.mail import EmailMessage
            email = EmailMessage(
                    sender,
                    message,
                    sender_email,
                    ['barbara.kacin@gmail.com'],
                    reply_to=[sender_email],
                )
            email.send(fail_silently=False)
            return render(request, 'barbara/contact.html', {'sender_name': sender_name})
    else:
        form = ContactForm()
    return render(request, 'barbara/contact.html', {'form': form})

def services(request):
    return render(request, 'barbara/services.html')

def set_language_from_url(request, user_language):
    translation.activate(user_language)
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/barbara/about.html
{% extends 'barbara/base.html' %}
{% load static %}
{% load i18n %}

{% block body_block %} 

<nav class="nav">
  <div class="container-fluid">
      <div>
      <a href="{% url 'barbara:index' %}"><img class="img_logo_2" src="{% static 'images/logo_pink.svg' %}" alt="logo"></a>
      </div>
    
    <div id="mainListDiv" class="main_list">
      <ul class="navlinks" id="black">
        <li><a href="{% url 'barbara:index' %}">{% trans "Domov" %}</a></li>
        <li><a class="current" href="{% url 'barbara:about' %}">{% trans "O Barbari" %}</a></li>
        <li><a href="{% url 'barbara:services' %}">{% trans "Ponudba" %}</a></li>
        <li><a href="{% url 'barbara:contact' %}">{% trans "Kontakt" %}</a></li>
      </ul>
    </div>
    <span class="navTrigger" id="pink">
      <i></i>
      <i></i>
      <i></i>
    </span>
  </div>
</nav>	

<!--- compressed menu function -->
<script>
$('.navTrigger').click(function () {
  $(this).toggleClass('active');
  console.log("Clicked menu");
  $("#mainListDiv").toggleClass("show_list");
  $("#mainListDiv").fadeIn();

});
</script>


<section class="header-section"></section>
    <div class="container" style="padding-bottom: 2rem;">
      <p class="main-headings">{% trans "Spoznajte Barbaro" %}</p>
      <div class="row">
      <img id="Barbara2" src="{% static 'images/Barbara.jpg' %}" alt="Barbara">
      <div class="col-12">
        <img class="float-md-right" id="Barbara" src="{% static 'images/Barbara.jpg' %}" alt="Barbara">
  <p class="normal-text">{% trans "Barbara profesionalno opravlja vrhunske kozmetične storitve že skoraj 35 let. Pred tem je zaključila srednjo zdravstveno šolo in je sprva delala kot medicinska sestra. Kasneje je svoj interes v dobrobitju človeka prenesla na področje lepote in wellnessa. Na zavodu za tehnično izobraževanje je opravila še 2 leti kozmetične šole in se zaposlila kot kozmetičarka in maserka. Čez leta je nabrala bogate izkušnje v priznanih salonih in svoje znanje redno poglabljala z dodatnimi izobraževanji." %}</p>
  <p class="normal-text">{% trans "Barbaro je umetniška pot že od nekdaj zanimala, zato v prostem času rada ustvarja. Njena strast je zagotovo risanje s svinčnikom in slikanje z oljem na platno. Ima tudi izjemen obcutek za opremljanje in preoblikovanje. Uživa ob znanstveno-fantastičnih filmih in napetih romanih, ko pa ujame navdih pa napiše tudi kakšen verz." %}</p> 
  <p class="normal-text">{% trans "Zaradi večletnih izkušenj, umetniškega talenta in občutka za sočloveka ste v kozmetičnem salonu Barbara zagotovo v najboljših rokah." %}</p>
</div>
</div>
<hr>
<p class="normal-text">{% trans "Se vidimo!" %}</p>
  
<div id="bm"> </div>

<script src="bodymovin.js"></script>
<script src="js/lottie.js" type="text/javascript"></script>

<script>
  var animation = bodymovin.loadAnimation({
  container: document.getElementById('bm'),
  renderer: 'svg',
  loop: false,
  autoplay: true,
  path: '{% static "js/data.json" %}'
})
</script>

<p class="sub-headings">{% trans "Certifikati in izobrazba" %}</p>
<p class="normal-text" style="margin-left: 0; padding-left: 0;">
  &#9642&nbsp&nbsp&nbsp{% trans "Potrdilo o udeležbi na delavnici s parfumiranimi permanentnimi laki Parish (2019)" %}<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Certifikat za master course Combinal Eyelash Lifting" %} (2019)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Certifikat za opravljen IBX System Education Program (2017)" %}<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Certifikat za tečaj Podaljševanje trepalnic" %} (2014)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Potrdilo o izobraževanju Barbor tretmani za obraz in telo" %} (2011)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Potrdilo o udeležbi seminarja Terapevtska masaža hrbta" %} (2011)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Certifikat za udeležbo seminarja Limfna drenaža" %} (2011)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Potrdilo o opravljenem tečaju Klinične Aromaterapije po licenci Inštituta Eve Taylor, London" %} (2010)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Refleksivna masaža stopal" %} (2003)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Potrdilo o opravljenem tečaju pedikure Zti kozmetika (Zavod za tehnično izobraževanje)" %} (2001)<br>
  &#9642&nbsp&nbsp&nbsp{% trans "Potrdilo o izobrazbi in usposobljenju za poklic kozmetičarke (Zavod za tehnično izobraževanje)" %} (1989)<br>
  </p>
</div>
{% endblock %}

templates/barbara/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

<html>
	<head lang="en"> 
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="format-detection" content="telephone=no">
	<title>Kozmetični salon Barbara</title>
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="icon" href="{% static 'images/logo_pink.svg' %}">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.7.0/lottie.min.js"></script>
	<script src="{% static 'js/lottie.js' %}" type="text/javascript"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
		
	<link href="https://fonts.googleapis.com/css2?family=Charmonman:wght@700&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Cantata+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Prata&display=swap" rel="stylesheet">
	<script src='https://kit.fontawesome.com/a076d05399.js'></script>

	<link rel="stylesheet" href="{% static 'css/style.css' %}" />
	<link rel="stylesheet" href="{% static 'css/navigation.css' %}" />
	<link rel="stylesheet" href="{% static 'css/pricing-list.css' %}" />

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/pricing-list.js' %}"></script>
	<script src="{% static 'js/nav_bar.js' %}"></script>
	<script src="{% static 'js/up-button.js' %}"></script>
	</head>

<body>

<button onclick="topFunction()" id="myBtn" aria-hidden="true"><i class='fas'>&#xf106;</i></button>
<script>
	//Get the button:
	mybutton = document.getElementById("myBtn");

	// When the user scrolls down 20px from the top of the document, show the button
	window.onscroll = function() {scrollFunction()};

	function scrollFunction() {
	if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
		mybutton.style.display = "block";
	} else {
		mybutton.style.display = "none";
	}
	}

	// When the user clicks on the button, scroll to the top of the document
	function topFunction() {
	document.body.scrollTop = 0; // For Safari
	document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
	}
</script>

	<div>
		{% block body_block %} 
		{% endblock %}
	</div>

<!--- FOOTER -->
<footer>
	<div class="container-fluid">
		<div class="row" style="padding-top: 1rem; padding-bottom: 1rem;">
		  <div class="col-sm-6 col-md-6 col-lg-3 align-self-center" style="padding-bottom:0;">
	<section class="logo-section">
	<div class="my-auto" id="logo">
		<img src="{% static 'images/logo_white.svg' %}" alt="logo"><br>
		<p class="footer-logo-salon">{% trans "kozmetični salon" %}</p>
		<p class="footer-logo-barbara">BARBARA</p>
	</div>
</section>
</div>

	<div class="col-sm-6 col-md-6 col-lg-2" style="padding-top: 30px;">
	<div class="footer-left">
	<p class="footer_headings">{% trans "Meni" %}</p>
	<ul style="list-style-type:none; padding:0; text-align: center;">
	<li><a class="footer-menu" href="{% url 'barbara:index' %}">{% trans "Domov" %}</a></li>
	<li><a class="footer-menu" href="{% url 'barbara:about' %}"><center>{% trans "O Barbari" %}</center></a></li>
	<li><a class="footer-menu" href="{% url 'barbara:services' %}"><center>{% trans "Ponudba" %}</center></a></li>
	<li><a class="footer-menu" href="{% url 'barbara:contact' %}"><center>{% trans "Kontakt" %}</center></a></li>
	</ul>
</div>
</div>

<div class="col-sm-12 col-md-6 col-lg-3" style="padding-top: 30px;">
<div class="footer-center">
<div><p class="footer_headings">{% trans "Odpiralni čas" %}</p>
<p><center>{% trans "Po dogovoru" %}.</center></p></div>
<hr>
<div><center><img class="icon" src="{% static 'images/navigation.png' %}">Savska cesta 20, 4270 Jesenice, SI</center>
<a href="{% url 'barbara:contact' %}#navigacija"><center><p class="link-text" style="color: #DA7EC4;">{% trans "Zemljevid in navodila za pot" %}</p></center></a></div>
<hr>
</div>
</div>

<div class="col-sm-12 col-md-6 col-lg-4" style="padding-top: 30px;">
<div class="footer-right">
<p class="footer_headings">{% trans "Kontakt" %}</p>

<div><img class="icon" src="{% static 'images/call.jpg' %}"><a href="tel:+386 41 429 948" style="color: inherit;"> +386 41 429 948</a></div>
<br>
<div><img class="icon" src="{% static 'images/at.png' %}"><a href="mailto:barbara.kacin@gmail.com?subject=Rezervacija%20termina" style="color: inherit;"> barbara.kacin@gmail.com</a></div>
</div>
</div>
</div>
</div>
<p id="pink-footer"><a href="{% url 'set_language_from_url' user_language='sl' %}">SL </a>/<a href="{% url 'set_language_from_url' user_language='en' %}"> EN</a></p>
</footer>
</body>
</html>

templates/barbara/contact.html
{% extends 'barbara/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block body_block %}

<nav class="nav">
  <div class="container-fluid">
      <div>
      <a href="{% url 'barbara:index' %}"><img class="img_logo_2" src="{% static 'images/logo_pink.svg' %}" alt="logo"></a>
      </div>
    
    <div id="mainListDiv" class="main_list">
      <ul class="navlinks" id="black">
        <li><a href="{% url 'barbara:index' %}">{% trans "Domov" %}</a></li>
        <li><a href="{% url 'barbara:about' %}">{% trans "O Barbari" %}</a></li>
        <li><a href="{% url 'barbara:services' %}">{% trans "Ponudba" %}</a></li>
        <li><a class="current" href="{% url 'barbara:contact' %}">{% trans "Kontakt" %}</a></li>
      </ul>
    </div>
    <span class="navTrigger" id="pink">
      <i></i>
      <i></i>
      <i></i>
    </span>
  </div>
</nav>	

<!--- compressed menu function -->
<script>
$('.navTrigger').click(function () {
  $(this).toggleClass('active');
  console.log("Clicked menu");
  $("#mainListDiv").toggleClass("show_list");
  $("#mainListDiv").fadeIn();

});
</script>


<section class="header-section">
</section>
<section class="header2-section">
  
</section>

<div class="container">
<p class="main-headings" style="text-align: center;">{% trans "Kontakt" %}</p>
<div class="row justify-content-center">
  <div class="col-lg-4 col-md-6 col-sm-12 my-auto">
    <div class="row">
      <div class="col-xl-2 col-lg-3 col-2 my-auto">
        <object class="svg_logo" type="image/svg+xml" data="{% static 'images/call.svg' %}" width="70px" height="70px"></object>
      </div>
      <div class="col-xl-8 col-lg-9 col-8 my-auto" style="line-height: 35px;">
        <p class="contact-headings">&nbsp&nbsp{% trans "Telefon" %}</p>
        <p>&nbsp&nbsp+386 41 429 948</p>
      </div>
    </div>
  </div>

  <div class="col-lg-4 col-md-6 col-sm-12 my-auto">
    <div class="row">
      <div class="col-xl-2 col-lg-3 col-2 my-auto">
        <object class="svg_logo" type="image/svg+xml" data="{% static 'images/at.svg' %}" width="70px" height="70px"></object>
      </div>
      <div class="col-xl-8 col-lg-9 col-8 my-auto" style="line-height: 35px;">
        <p class="contact-headings">&nbsp&nbsp{% trans "E-pošta" %}</p>
        <p>&nbsp&nbspbarbara.kacin@gmail.com</p>
      </div>
    </div>
  </div>

  <div class="col-lg-4 col-md-12 my-auto">
    <div class="row">
      <div class="col-xl-2 col-lg-3 col-md-1 col-2 my-auto">
        <object class="svg_logo" type="image/svg+xml" data="{% static 'images/time.svg' %}" width="70px" height="70px"></object>
      </div>
      <div class="col-xl-8 col-lg-9 col-10 my-auto" style="line-height: 35px;">
        <p class="contact-headings">&nbsp&nbsp{% trans "Odpiralni čas" %}</p>
        <p>&nbsp&nbsp{% trans "Po dogovoru" %}.</p>
      </div>
    </div>
  </div>
</div>

<hr>

<p class="sub-headings" style="text-align: center; padding-top: 2rem;">{% trans "Piši mi" %}</p>
{% if sender_name %}
<p class="normal-text" style="text-align: center">{% trans "Hvala za sporočilo! Odgovorili bomo v najkrajšem možnem času" %}.</p>

{% else %}
<img class="contact-me-small" src="{% static 'images/woman.jpg' %}" alt="woman_on_computer">
<div class="row justify-content-center" id="contact-me-section">
  <div class="col-xl-6 col-lg-7 col-md-10" style="margin-top: 10px; margin-bottom: 10px;">
    <form method="POST">
      {% csrf_token %}
      {% crispy form %}
    </form>
  </div>    
</div>
{% endif %}

<p class="sub-headings" style="text-align: center;  padding-top: 2rem;">{% trans "Kje me najdeš" %}</p>
<div class="row justify-content-center">
<object class="svg_logo" type="image/svg+xml" data="{% static 'images/navigation.svg' %}" width="70px" height="70px"></object>
<p class="normal-text" style="line-height: 70px;">&nbsp&nbspSavska cesta 20, 4270 Jesenice.</p>
</div>
</div>

<div id="navigacija">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2750.250499797288!2d14.081250614988159!3d46.423914276914!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x477a9a7e1eab9fcd%3A0x5dd07e3c3e0c9f04!2sBarbara%20Torkar%20Dov%C5%BEan%20s.p.!5e0!3m2!1ssl!2ssi!4v1590396297994!5m2!1ssl!2ssi" class="google_map" allowfullscreen="" frameBorder="0" aria-hidden="false" tabindex="0"></iframe>
</div>
{% endblock %}

templates/barbara/index.html
{% extends 'barbara/base.html' %}
{% load static %}
{% load i18n %}

{% block body_block %} 

<nav class="nav">

    <div class="container-fluid">
        <div id="mainListDiv" class="main_list">
            <ul class="navlinks" id="white">
                <li><a class="current" href="{% url 'barbara:index' %}">{% trans "Domov" %}</a></li>
                <li><a href="{% url 'barbara:about' %}">{% trans "O Barbari" %}</a></li>
                <li><a href="{% url 'barbara:services' %}">{% trans "Ponudba" %}</a></li>
                <li><a href="{% url 'barbara:contact' %}">{% trans "Kontakt" %}</a></li>
            </ul>
        </div>
        <span class="navTrigger" id="white">
            <i></i>
            <i></i>
            <i></i>
        </span>
    </div>
</nav>	

<!--- compressed menu function -->
<script>
$('.navTrigger').click(function () {
    $(this).toggleClass('active');
    console.log("Clicked menu");
    $("#mainListDiv").toggleClass("show_list");
    $("#mainListDiv").fadeIn();

});
</script>

<div class="container-fluid">
<div class="video-section">
<video loop="true" autoplay="autoplay" controls muted>
    <source src="{% static 'images/breezy_girl.mp4' %}" type="video/mp4;codecs=&quot;avc1.42E01E, mp4a.40.2&quot;">
</video>
<div class="video-label">
    <div class="welcome-text">
        <a href="{% url 'barbara:index' %}"><img class="img_logo" src="{% static 'images/logo_white.svg' %}" alt="logo"></a>
        <p><span class="b">{% trans "kozmetični salon" %}</span><p>
        <p><span class="c">BARBARA</span></p>
        <p class="a">{% trans "Dobrodošli!" %}</p>
        <form><button class="book_button" formaction="{% url 'barbara:contact' %}" id="other">{% trans "Naročite se" %}</button></form>
    <div class="language"><a href="{% url 'set_language_from_url' user_language='sl' %}">SL </a>/<a href="{% url 'set_language_from_url' user_language='en' %}"> EN</a></div>

</div>

</div>

<section style="margin-bottom: 5rem;">
<p class="sub-headings" style="margin-top: 3rem; text-align: center;">{% trans "Ponudba" %}</p>
<p class="normal-text" style="text-align: center; margin-top:-10px;">{% trans "Oglejte si raznoliko ponudbo storitev za celotno telo." %}</p>
<div class="row justify-content-center md-ml-6 md-mr-6" style="padding-top: 15px;">
    <div class="col-auto" style="position: relative;">
    <a class="offer-container" href="{% url 'barbara:services' %}#obraz"><img class="circular--square" src="{% static 'images/obraz.jpeg' %}" alt="obraz">
    <p class="offer-shortcuts">{% trans "OBRAZ" %}</p></a>
</div>
<div class="col-auto" style="position: relative;">
    <a class="offer-container" href="{% url 'barbara:services' %}#roke"><img class="circular--square" src="{% static 'images/roke.jpeg' %}" alt="roke">
    <p class="offer-shortcuts">{% trans "ROKE" %}</p></a>
</div>
<div class="col-auto">
    <a class="offer-container" href="{% url 'barbara:services' %}#noge"><img class="circular--square" src="{% static 'images/noge.jpeg' %}" alt="noge">
    <p class="offer-shortcuts">{% trans "NOGE" %}</p></a>
</div>
<div class="col-auto">
    <a class="offer-container" href="{% url 'barbara:services' %}#depilacije"><img class="circular--square" src="{% static 'images/depilacije.jpeg' %}" alt="depilacije">
    <p class="offer-shortcuts">{% trans "DEPILACIJE" %}</p></a>
</div>
<div class="col-auto">
    <a class="offer-container" href="{% url 'barbara:services' %}#masaze"><img class="circular--square" src="{% static 'images/masaze.jpeg' %}" alt="masaze">
    <p class="offer-shortcuts">{% trans "MASAŽE" %}</p></a>
</div>
</div>
</section>
</div>


<div id="about-section" class="row justify-content-center">
    <p class="about-text">{% trans "Spoznajte Barbaro." %}&nbsp&nbsp</p>  
    <form><button formaction="{% url 'barbara:about' %}" class="book_button" id="other">{% trans "preberi več" %}</button></form>
</div>

    <div class="row" id="reservation-section">
            <img class="reservation-image" src="{% static 'images/planner.jpg' %}" alt="serum">
        <div class="col-lg align-self-center" style="padding-top: 1rem; padding-bottom: 1rem;" id="reservation-box">
                <p class="one">{% trans "vabljeni" %}!<br></p>
                <p class="two">{% trans "rezervirajte termin" %}</p>
                <hr width="80%">
                <p class="three">{% trans "Barbarin delovnik poteka po dogovoru" %}. <br> {% trans "Naročite se prek telefona ali e-maila" %}.<br><br></p>
                <div class="row">
                    <div class="col-sm-6">
                        <form class="number">
                            <button formaction="tel:+386 41 429 948" class="book_button" id="reservation-box">+386 41 429 948</button>
                        </form>
                    </div>
                    <div class="col-sm-6">
                        <form class="email">
                            <button formaction="mailto:barbara.kacin@gmail.com?subject=Rezervacija%20termina" class="book_button" id="reservation-box">
                                barbara.kacin@gmail.com</button>
                        </form>
                    </div>
                </div>
        </div>
    </div>
</div>

{% endblock %}